version: '3.8'

services:
  # 1. THE DATABASE
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: traffic_monitor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. THE BACKEND
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=traffic_monitor
      - JWT_SECRET=supersecretjwtkey123
    depends_on:
      - db

  # 3. THE FRONTEND
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: